Tenderator/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('invoice/', include('invoice.urls')),
    path('admin/', admin.site.urls),
    path('', views.redirect_view)
]

invoice/urls.py
from django.urls import path

from . import views

app_name = 'invoice'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('save/', views.save_invoice_to_csv, name='save_invoice_to_csv'),
    path('save/<str:categories_and_manufacturers>', views.save_invoice_to_csv, name='save_invoice_to_csv'),
    path('save_as_xls/<str:categories_and_manufacturers>', views.save_invoice_as_xls, name='save_invoice_as_xls'),
    path('save_as_xls/', views.save_invoice_as_xls, name='save_invoice_as_xls'),


]

invoice/models.py
from django.db import models


# Create your models here.

class Manufacturer(models.Model):
    manufacturer_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.manufacturer_name


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'


class Device(models.Model):
    device_name = models.CharField(max_length=200, unique=True)
    device_description = models.TextField(null=True)
    device_manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    device_category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.device_name

Tenderator/views.py
from django.http import HttpResponse
from django.shortcuts import redirect


def redirect_view(request):
    response = redirect('http://127.0.0.1:80/invoice')
    return redirect('invoice:index')

invoice/views.py
import io

from django.http import HttpResponse, FileResponse, StreamingHttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic

from .models import Device, Category, Manufacturer
import os
import pandas
from io import StringIO

from django.conf import settings as django_settings
from django.http import HttpResponse
from .resources import DeviceResource


# Create your views here.
class DetailView(generic.DetailView):
    model = Device
    template_name = 'invoice/device_details.html'


def index(request):
    devices = Device.objects.all().order_by('device_category', 'device_manufacturer')

    devices_ordered = {}

    for device in devices:
        if device.device_category not in devices_ordered.keys():
            devices_ordered[device.device_category] = {}
        if device.device_manufacturer not in devices_ordered[device.device_category].keys():
            devices_ordered[device.device_category][device.device_manufacturer] = []

        devices_ordered[device.device_category][device.device_manufacturer].append(device)

    print(devices_ordered)
    context = {
        'devices': devices,
        'devices_ordered': devices_ordered,

    }

    return render(request, 'invoice/device_list.html', context)


def save_invoice_to_csv(request, categories_and_manufacturers=''):
    print('start')
    print(categories_and_manufacturers)
    print(django_settings.STATIC_ROOT)
    import csv

    # with open('invoice.csv', 'w', newline='', encoding='utf-8') as csvfile:
    try:
        filepath = os.path.join(django_settings.STATIC_ROOT, 'invoice.csv')
        csvfile = open(filepath, 'w', newline='', encoding='utf-8')
    except FileNotFoundError:
        filepath = os.path.join('static', 'invoice.csv')
        csvfile = open(filepath, 'w', newline='', encoding='utf-8')

    with csvfile as csvfile:
        writer = csv.writer(csvfile, delimiter=' ')

        for elem in categories_and_manufacturers.split(";"):
            category = elem[:elem.find(":")].strip()
            manufacturer = elem[elem.find(":") + 1:].strip()
            writer.writerow([category])
            writer.writerow([manufacturer])
            print(elem, " --", category, '+', manufacturer, sep='')

            devices = Device.objects \
                .filter(device_category__category_name=category, device_manufacturer__manufacturer_name=manufacturer) \
                .order_by('device_category', 'device_manufacturer')

            for device in devices:
                writer.writerow([device.device_name, device.device_description, "some other data"])

    return FileResponse(open(filepath, 'rb'))
    # return redirect('invoice:index')


def save_invoice_as_xls(request, categories_and_manufacturers=''):
    print(categories_and_manufacturers)
    columns_list = ['id', 'device_name', 'device_description', 'device_manufacturer', 'device_category']
    results_date_frame = pandas.DataFrame([], columns=columns_list)

    for elem in categories_and_manufacturers.split(";"):
        try:
            category = int(elem[:elem.find(":")].strip())
            manufacturer = int(elem[elem.find(":") + 1:].strip())
        except ValueError:
            print('here is some problem')
            continue
        print('category: ', category, type(category))
        print('manufacturer: ', manufacturer)
        devices = Device.objects \
            .filter(device_category_id=category, device_manufacturer_id=manufacturer) \
            .order_by('device_category', 'device_manufacturer')

        for device in devices:
            attributes_dict = {}
            for column_name in columns_list:
                attributes_dict[column_name] = getattr(device, column_name)

            results_date_frame = pandas.concat([results_date_frame, pandas.DataFrame(attributes_dict, index=[0])],
                                               ignore_index=True)

    with io.BytesIO() as b:
        with pandas.ExcelWriter(b) as writer:
            results_date_frame.to_excel(writer, index=False)

        res = HttpResponse(
            b.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        res['Content-Disposition'] = 'attachment; filename=invoice.xlsx'
        return res

Tenderator/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}Title {% endblock %}</title>
</head>
<body>
{% block header %}
    <div class="row">
        <div class="col">
            <a href="{% url 'admin:index' %}"><h3>Admin</h3></a>
        </div>

    </div>

{% endblock %}
{% block body %}
    Main index
{% endblock body %}

{% block javascript %}
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
{% endblock javascript %}
</body>

</html>

Tenderator/templates/invoice/device_details.html
{% extends 'index.html' %}
{% block title %} this is new title {% endblock title %}
{% block body %}
    <div class="container bg-light">
        <div class="row">
            <div class="col">
                {{ device.id }} {{ device.device_name }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ device.device_category }} {{ device.device_manufacturer }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ device.device_description }}
            </div>

        </div>
    </div>

{% endblock body %}

Tenderator/templates/invoice/device_list.html
{% extends '../index.html' %}
{% block title %} this is new title {% endblock title %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-3 sticky-top">
                <div class="row mb-4  sticky-top">
                    <div class="col">
                        <ul class="list-group ">
                            {% for category, manufacturer in devices_ordered.items %}
                                {% if category.category_name|length > 0 %}
                                    <li class="list-group-item bg-dark text-white">
                                        <div class="row">
                                            <div class="col">
                                                <a class="text-decoration-none text-white"
                                                   href="#{{ category.category_name }}">
                                                    {{ category.category_name }}
                                                </a>
                                            </div>
                                            <div class="col">
                                                <div class="form-check form-switch float-end">
                                                    <input class="form-check-input {{ category.category_name }}"
                                                           type="checkbox"
                                                           id="{{ category.category_name }}" checked>
                                                    <label class="form-check-label"
                                                           for="flexSwitchCheckChecked"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item ">
                                        <ul class="list-group">
                                            {% for manufacturer, devices in manufacturer.items %}
                                                <li class="list-group-item bg-secondary bg-gradient text-white">
                                                    <div class="row">
                                                        <div class="col">

                                                            <a class="text-decoration-none text-white"
                                                               href="#{{ category }}{{ manufacturer }}">
                                                                {{ manufacturer }}
                                                            </a>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-check form-switch  float-end">
                                                                <input class="form-check-input manufacturerID_{{ manufacturer.id }} categoryID_{{ category.id }}"
                                                                       type="checkbox" id="flexSwitchCheckChecked"
                                                                       checked>
                                                                <label class="form-check-label manufacturer"
                                                                       for="flexSwitchCheckChecked"></label>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </li>

                                            {% endfor %}

                                        </ul>
                                    </li>

                                {% endif %}
                            {% endfor %}
                            <li class="list-group-item text-decoration-none">
                                <a href="{% url 'invoice:save_invoice_as_xls'  categories_and_manufacturers='?' %}"
                                   id="xls_pandas_save_url">
                                    <button type="button" class="btn btn-success" id="xls_pandas_save_button">
                                        Save as XLS
                                    </button>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>

            </div>
            <div class="col">
                <table class="table table-striped">
                    {% for category, manufacturer in devices_ordered.items %}
                        {% if category.category_name|length > 0 %}
                            <tr class="bg-dark">
                                <th colspan="2" class="text-white"> {{ category.category_name }} <a
                                        id="{{ category.category_name }}"></a></th>
                            </tr>

                            {% for manufacturer, devices in manufacturer.items %}
                                <tr class="bg-secondary">
                                    <th colspan="2" class="text-white"> {{ manufacturer }}
                                        <a id="{{ category }}{{ manufacturer }}"></a></th>
                                </tr>

                                {% for device in devices %}
                                    <tr>
                                        <td>{{ device.device_name }}</td>
                                        <td>{{ device.device_description }}</td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function () {

            {% for category, manufacturer in devices_ordered.items %}
                {% if category.category_name|length > 0 %}
                    $('.{{ category.category_name }}').change(function () {
                        if (this.checked) {
                            $('.categoryID_{{ category.id }}').prop('checked', true);
                        } else {
                            $('.categoryID_{{ category.id }}').prop('checked', false);
                        }
                    });
                {% endif %}
            {% endfor %}

            $('#xls_pandas_save_button').on('click', function (event) {
                event.preventDefault();
                let categories_to_save = ""
                $(".form-check-input").each(function () {
                    if (this.checked) {
                        let classList = this.className.split(/\s+/);
                        let category_to_save = ""
                        let manufacturer_to_save = ""
                        classList.forEach(function (entry) {
                            if (entry.startsWith('categoryID_')) {
                                category_to_save = entry.substring('categoryID_'.length)
                            }
                            if (entry.startsWith('manufacturerID_')) {
                                manufacturer_to_save = entry.substring('manufacturerID_'.length)
                            }
                        });
                        if (manufacturer_to_save > 0) {
                            categories_to_save = categories_to_save + category_to_save + ":" + manufacturer_to_save + ";"
                        }
                    }
                });


                console.log(categories_to_save)
                {#here need to parse all checkboxes and send this data to the view as categories_and_manufacturers variable#}
                {#Category1:brand1;Category1:brand2;Category1:brand3;Category2:brand1...#}
                {#$('#csv_save_url').attr("href", generate_save_invoice_to_csv_url(categories_to_save))#}
                window.location.href = generate_save_invoice_to_xls_url(categories_to_save);
            });


            function generate_save_invoice_to_xls_url(selected_categories_and_manufacturers) {
                return "{% url 'invoice:save_invoice_as_xls' categories_and_manufacturers='!' %}".replace("!", selected_categories_and_manufacturers);
            }
        });
    </script>
{% endblock javascript %}